### ISSUE TITLE
Error en instalación de dependencias

### ISSUE THREAD

**Issue by migpalg** [MachinEmmus/cv#1]
Puedes instalar todas las dependencias haciendo solamente una vez

```
npm install
```

Sobre la carpeta que está el paquete

**Comment by MachinEmmus** [comment]
Oe ahhh bueno gracias por la informacion parce

**Comment by MachinEmmus** [comment]
Queda claro que situado en el folder con
 ´´´
npm install 
´´´
se descargan las dependencias necesarias para el proyecto
